#!/bin/sh
# This makes X work when I su to root.
if [ -z "$XAUTHORITY" ]; then
        XAUTHORITY=$HOME/.Xauthority
        export XAUTHORITY
fi

# Keep very sinple locale as default
# set specific in .bashrc for each $TERM types

unset LC_ALL
export LANG=C
export LANUAGE=C

# Japanese locale as default, C locale as backup
#LANG=ja_JP.eucJP     
#export LANG
# make sure to over write en_US.ISO-8859-1 used in console
#LC_CTYPE=ja_JP.eucJP
#export LC_CTYPE
# I want menu message to be English in ASCII :-)
#LC_MESSAGES=C
#export LC_MESSAGES

###
# activate input method
kinput2 &        
XMODIFIERS=@im=kinput2
export XMODIFIERS

# How about blackbox window manager (lightweight)
#exec /usr/bin/blackbox
#exec xfwm
#exec fluxbox

exec blackbox

