#!/bin/sh -e
# Copyright (C) 2011 Osamu Aoki <osamu@debian.org>, Public Domain
case $1 in
ca)
echo "Catalan"
;;
de)
echo "German"
;;
en)
echo "English"
;;
es)
echo "Spanish"
;;
fr)
echo "French"
;;
it)
echo "Italian"
;;
ja)
echo "Japanese"
;;
ko)
echo "Korean"
;;
pt)
echo "Portuguese"
;;
pt-br)
echo "Portuguese(br)"
;;
zh-cn)
echo "Chinese(cn)"
;;
zh-tw)
echo "Chinese(tw)"
;;
*)
echo "$1"
;;
esac

