#
# Makefile for the release notes, language subdirectory
#

# increase (font?) memory size for Chinese documents in Woody
export TEXMFCNF=../../quick-reference/texmf:

include $(CURDIR)/../Makefile.common

