#!/bin/sh
# Copyright (C) 2009 Osamu Aoki <osamu@debian.org>
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# You can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 or later.
# 
# Merge all PO files smartly
#
#    po4a-uniq file1 file2 file3 file4  >file-out
#
{
  for i in "$@" ; do
    cat $i
  done
} | msguniq --use-first --no-wrap
#
#
# vim: set sts=2 ai expandtab:

