#!/bin/sh
# Copyright (C) 2009 Osamu Aoki <osamu@debian.org>
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# You can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 or later.
# 
# Extract all PO files smartly
#
#    po4a-extract file1 file2 file3 file4
#
for i in "$@" ; do
  ii=${i%.po}
  msgattrib --untranslated  --no-wrap $i  >$ii.extract.po
  msgattrib --fuzzy  --no-wrap        $i >>$ii.extract.po
done
#
#
# vim: set sts=2 ai expandtab:

