#!/bin/sh
# Copyright (C) 2009 Osamu Aoki <osamu@debian.org>
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# You can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 or later.
# 
# Merge all PO files smartly
#
#    po4a-merge file1 file2 file3 file4  >file-out
#
for i in "$@" ; do
  ii=${i%.po}
  msgattrib --untranslated --no-fuzzy --no-obsolete --no-wrap $i >$ii.untranslated.po
  msgattrib --translated --fuzzy --no-obsolete --no-wrap $i >$ii.fuzzy.po
  msgattrib --translated --no-fuzzy --obsolete --no-wrap $i >$ii.obsolete.po
done

{
  for i in "$@" ; do
    ii=${i%.po}
    cat $ii.untranslated.po
  done
  for i in "$@" ; do
    ii=${i%.po}
    cat $ii.fuzzy.po
  done
  for i in "$@" ; do
    ii=${i%.po}
    cat $ii.obsolete.po
  done
} | msguniq --use-first --no-wrap
#
#
# vim: set sts=2 ai expandtab:

