#!/bin/sh
# Copyright (C) 2009 Osamu Aoki <osamu@debian.org>
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# You can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 or later.
# 
# Strip header out of PO file.
#
#    po4a-strip file-in >file-out
#
sed -n -e '1,/^$/!p'
#
#
# vim: set sts=2 ai expandtab:

