#!/bin/sh
# Copyright (C) 2009 Osamu Aoki <osamu@debian.org>
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# You can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 or later.
# 
# Strip header out of PO file.
#
#    zcat debian-reference.??.txt.gz | wordlist >word.list
#
sed -e "s/['│]/ /g" -e 's/"/ /g' -e "s/[.:;,] / /g" -e "s/[)] / /g" -e "s/ [(]/ /g"|\
xargs -n1 echo |\
grep -v "[-0-9/.:;,─━©—^~|_<>#()]" |\
grep -v "^$"|\
sort|uniq
#
#
# vim: set sts=2 ai expandtab:

