#!/bin/sh

set -e

case "$1" in
    configure)
        # continue below
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/developers-reference -a -d /usr/share/doc/developers-reference ]; then
    ln -sf ../share/doc/developers-reference /usr/doc/developers-reference
  fi
fi

if [ -x /usr/sbin/install-docs ]; then
    /usr/sbin/install-docs -i /usr/share/doc-base/developers-reference
fi

exit 0
