#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if [ -x /usr/sbin/install-docs ]; then
        /usr/sbin/install-docs -i /usr/share/doc-base/developers-reference
        /usr/sbin/install-docs -i /usr/share/doc-base/developers-reference.fr
        /usr/sbin/install-docs -i /usr/share/doc-base/developers-reference.ja
    fi
fi

exit 0
