#!/bin/sh

if [ "$1" = "remove" -o "$1" = "upgrade" ]; then
  if [ -x /usr/sbin/install-docs ]; then
    install-docs -r developers-reference
  fi
  if [ -L /usr/doc/developers-reference ]; then
    rm -f /usr/doc/developers-reference
  fi
fi

exit 0
