#!/bin/sh

if [ "$1" = "remove" -o "$1" = "upgrade" ]; then
  if command -v install-docs >/dev/null 2>&1; then
    install-docs -r developers-reference
  fi
  if [ -L /usr/doc/developers-reference ]; then
    rm -f /usr/doc/developers-reference
  fi
fi

exit 0
