.\" Translated into german by Jens Seidel <tux-master@web.de>
.\"
.TH DEBIAN-REFERENCE 1 "1. Juli 2003" "Debian" "Debian"
.SH BEZEICHNUNG
debian-reference \- Handbuch für die Zeit nach der Installation
.SH "ÜBERSICHT"
.br
.B debian-reference
.SH BESCHREIBUNG
Dies ist ein kleines Skript, das den bevorzugten Browser startet und die
Indexseite
.I file:/usr/share/doc/Debian/reference/reference.??.html
des debian-reference Dokumentationspaketes darstellt.  Die Sprache wird
entsprechend der locale Einstellung gewählt.
.SH UMGEBUNGSVARIABLEN
.IP BROWSER
Der Browser der zur Anzeige der HTML Dateien genutzt wird.
.IP LANG
Die anzuzeigende Sprache.
.IP LANGUAGE
Eine durch Doppelpunkte getrennte Liste von bevorzugten Sprachen.  Die erste
verfügbare Sprache wird verwendet, wenn die locale Einstellung von "C"
verschieden ist.

Wenn sowohl LANG als auch LANGUAGE gesetzt sind, wird LANGUAGE verwendet.
.SH AUTOR
Osamu Aoki (osamu@debian.org). 
.PP
Dieses Dokument kann unter den Bedingungen der GNU General Public License
Version 2 oder höher genutzt werden.
