
DOC = release-notes
lang = fr

POT = $(DOC).pot
PO = $(DOC).$(lang).po

SGML_ORIG = ../en/$(DOC).en.sgml
SGML_L10N = $(DOC).$(lang).sgml

update:
	debiandoc2pot $(SGML_ORIG) > $(POT)
	msgmerge -U $(PO) $(POT)
	po2debiandoc $(SGML_ORIG) $(PO) > $(SGML_L10N)

update-po:
	debiandoc2pot $(SGML_ORIG) > $(POT)
	msgmerge -U $(PO) $(POT)

stats:
	msgfmt -v -o /dev/null $(PO)

$(POT): $(SGML_ORIG)
	debiandoc2pot $? > $@

$(SGML_L10N): $(SGML_ORIG) $(PO)
	po2debiandoc $(SGML_ORIG) $(PO) > $@

.PHONY: update update-po stats
