.TH DEBIAN-REFERENCE 1 "November 10, 2002" "Debian" "Debian"
.SH NAME
debian-reference \- post-installation user's guide
.SH SYNOPSIS
file:///user/share/doc/Debian/reference/reference.??.html
.br
.B debian-reference
.SH DESCRIPTION
This is a small script that starts your favorite browser and displays
the index page of the debian-reference documentation package.
.SH ENVIRONMENT
.IP BROWSER
The browser used to display the HTML files.
.IP LANG
The choice of language.
.SH AUTHOR
Osamu Aoki (osamu@debian.org). 
.PP
This document may used under the terms of the GNU General Public
License version 2 or higher.
