.\" Translated into polish by Bartosz Feñski <fenio@o2.pl>
.\" Updated September 13, 2003, please update next line!
.TH DEBIAN-REFERENCE 1 "13 wrze¶nia, 2003" "Debian" "Debian"
.SH NAZWA
debian-reference \- poinstalacyjny przewodnik dla u¿ytkownika
.SH SK£ADNIA
.br
.B debian-reference
.SH OPIS
To jest ma³y skrypt, który uruchamia twoj± ulubion± przegl±darkê
i wy¶wietla stronê ze spisem tre¶ci 
.I file:/usr/share/doc/Debian/reference/index.html
dokumentacji zawartej w pakiecie debian-reference.
.SH ZMIENNE ¦RODOWISKOWE
.IP BROWSER
Przegl±darka u¿ywana do wy¶wietlania plików HTML.

.SH AUTOR
Osamu Aoki (osamu@debian.org). 
.PP
Ten dokument mo¿e byæ wykorzystywany zgodnie z postanowieniami GNU General
Public License w wersji 2 lub wy¿szej.
