.TH DEBIAN-REFERENCE 1 "13 de Setembro de 2003" "Debian" "Debian"
.SH NOME
debian-reference \- guia do usuário pós-instalação
.SH SINOPSE
.br
.B debian-reference
.SH DESCRIÇÃO
Esse é um pequeno script que inicia seu navegador favorito e exibe a
página de índice
.I file:/usr/share/doc/Debian/reference/index.html
do pacote de documentação debian-reference.
.SH AMBIENTE
.IP BROWSER
O navegador usado para exibir os arquivos HTML.

.SH AUTOR
Osamu Aoki (osamu@debian.org).
.PP
Este documento pode ser usado sob os termos da Licença Pública Geral
GNU versão 2 ou superior.
