.TH DEBIAN-REFERENCE 1 "September 13, 2003" "Debian" "Debian"
.SH NAME
debian-reference \- guida per l'utente post-installazione
.SH SYNOPSIS
.br
.B debian-reference
.SH DESCRIPTION
Questo è un piccolo script che lancia il vostro browser preferito e mostra
la pagina con l'indice
.I file:/usr/share/doc/Debian/reference/index.html
del pacchetto contenente la documentazione della guida Debian.
.SH ENVIRONMENT
.IP BROWSER
Il browser utilizzato per aprire i file HTML.

.SH AUTHOR
Osamu Aoki (osamu@debian.org). 
.PP
Questo documento è utilizzabile secondo i termini della GNU General Public
License versione 2 o maggiore.
