.TH DEBIAN-REFERENCE 1 "September 13, 2003" "Debian" "Debian"
.SH NAME
debian-reference \- post-installation user's guide
.SH SYNOPSIS
.br
.B debian-reference
.SH DESCRIPTION
This is a small script that starts your favorite browser and displays
the index page
.I file:/usr/share/doc/Debian/reference/index.html
of the debian-reference documentation package.
.SH ENVIRONMENT
.IP BROWSER
The browser used to display the HTML files.

.SH AUTHOR
Osamu Aoki (osamu@debian.org). 
.PP
This document may be used under the terms of the GNU General Public
License version 2 or higher.
