.TH DEBIAN-REFERENCE 1 "July 1, 2003" "Debian" "Debian"
.SH NAME
debian-reference \- post-installation user's guide
.SH SYNOPSIS
.br
.B debian-reference
.SH DESCRIPTION
This is a small script that starts your favorite browser and displays
the index page
.I file:/usr/share/doc/Debian/reference/reference.??.html
of the debian-reference documentation package.  The language is chosen
according to the locale settings.
.SH ENVIRONMENT
.IP BROWSER
The browser used to display the HTML files.
.IP LANG 
The choice of language.
.IP LANGUAGE
A colon separated list of preferred languages.  The first available language
will be used, if locale is not set to "C".

If both LANG and LANGUAGE are specified, LANGUAGE wins.
.SH AUTHOR
Osamu Aoki (osamu@debian.org). 
.PP
This document may used under the terms of the GNU General Public
License version 2 or higher.
