.TH DEBIAN-REFERENCE 1 "September 13, 2003" "Debian" "Debian"
.SH NAME
debian-reference \- guide de l'utilisateur post-installation
.SH SYNOPSIS
.br
.B debian-reference
.SH DESCRIPTION
Petit script qui démarre votre navigateur favori et affiche la page de
démarrage
.I file:/usr/share/doc/Debian/reference/index.html
du paquet de documentation debian-reference.
.SH ENVIRONMENT
.IP BROWSER
Le navigateur utilisé pour afficher les fichiers HTML.

.SH AUTHOR
Osamu Aoki (osamu@debian.org). 
.PP
Ce document peut être utilisé selon les termes de la GNU General Public License
version 2 ou supérieure.
