#!/bin/sh
# POSIX compliant script to search browser
set -e # stop at first error
#set -x # debug output

BDOCUMENTSTEM="/usr/share/doc/Debian/reference"
CBROWSERLIST="/usr/bin/www-browser /usr/bin/elinks /usr/bin/links /usr/bin/w3m /usr/bin/lynx"
XBROWSERLIST="/usr/bin/x-www-browser /usr/bin/mozilla /usr/bin/X11/galeon /usr/bin/amaya /usr/bin/X11/netscape /usr/bin/gnome-help-browser /usr/bin/dillo"

#echo check whether BROWSER environment var exist or not >&2
# Sanity check
if [ $BROWSER ] && ! type $BROWSER >/dev/null 2>/dev/null; then
  echo "$0: WWW browser (BROWSER=$BROWSER) does not exist." >&2
  exit 1
fi
# X environment
if [ "$DISPLAY" ] && ! [ $BROWSER ]; then
  echo check whether X browsers exist or not in X environment >&2
  for BROWSER in $XBROWSERLIST; do
    if [ -x $BROWSER ]; then
      break
    fi
  done
fi
# Console environment
if ! [ $BROWSER ]; then
  echo check whether console browsers exist or not >&2
  for BROWSER in $CBROWSERLIST; do
    if [ -x $BROWSER ]; then
      [ "$DISPLAY" ] && BROWSER="/usr/bin/x-terminal-emulator -e $BROWSER"
      break
    fi
  done
fi

if [ -r $BDOCUMENTSTEM/index.html ]; then
  $BROWSER $BDOCUMENTSTEM/index.html
fi
