#! /bin/sh -e
if   [ "$1" == "en" ] ; then echo "<dt>English</dt>"
elif [ "$1" == "fr" ] ; then echo "<dt>French</dt>"
elif [ "$1" == "it" ] ; then echo "<dt>Italian</dt>"
elif [ "$1" == "es" ] ; then echo "<dt>Spanish</dt>"
elif [ "$1" == "fi" ] ; then echo "<dt>Finish</dt>"
elif [ "$1" == "de" ] ; then echo "<dt>German</dt>"
elif [ "$1" == "ja" ] ; then echo "<dt>Japanese</dt>"
elif [ "$1" == "pt-br" ] ; then echo "<dt>Portuguese (Brazil)</dt>"
else echo "<dt>$1</dt>"
fi

echo "<dd>"
echo "<a href=\"$2.$1.html\">HTML</a>,"
echo "<a href=\"$2.$1.txt\">plain text</a>,"
echo "<a href=\"$2.$1.ps\">PS</a>,"
echo "<a href=\"$2.$1.pdf\">PDF</a>"
echo "</dd>"

