Hints:

In order for your browser to read all types of "Debian Reference", you have 
to configure your browser to be able to read *.txt.gz and also invoke 
appropriate viewer to read compressed PS and PDF after decompressing.

You may need to refresh your browser to get proper list of documents.

Known problems and needed additions:

=== KNOWN BUGS/FEATURS ===
* Source is not UTF-8 (Unicode) but traditional encodings.
* &nbsp; comes out strange in <example> for PDF (still?).
* need to fix tab codes if they still exist in our source.
* FIXME sections ("XXX FIXME XXX") in source needs fix.
* aptitude needs to be used more often
* Need to mention that shell example are obtained after doing "unset PS2"
* Still minor issues remain for CJK PS/PDF files and Polish quotation.
* Translations lag their contents behind the English original
  - Chinese (zh-tw) is still a partial translation.
  - Finnish is stalled and will not be packaged in the current shape.
  - Sarge may be still broken for building this package for zh-* for PS/PDF.
    (Use Sid or Woody)
  - No Japanese started yet.  Shame on me.
  - Version status as below:
  ----------------------------------------------------------------------------
=== TODO ===
* Thinking about using po-debiandoc by Denis Barbier <barbier@debian.org> 
  to manage translation.
  http://people.debian.org/~barbier/devel/po-debiandoc/

* Thinking about moving to dookbook-xml

Please use Debian BTS for reporting bug or feature request with your
solid content proposal.  Submitting solid patch files are the best
contribution.

* To CVS read access of the latest source:

 $ export CVSROOT=:pserver:anonymous@cvs.qref.sf.net:/cvsroot/qref
 $ cvs login
 Logging in to :pserver:anonymous@cvs.qref.sf.net:2401/cvsroot/qref
 CVS password:
 $ cvs co -d debian-reference qref

For CVS write access, please contact me and read our development 
homepage:
   http://qref.sourceforge.net/doc

Osamu Aoki <debian@aokiconsulting.com>
Osamu Aoki <osamu@debian.org>

=== TIPS to be included soon or my own reminders ===

* RFCs on basic system daemon and related information.
  + POP3: rfc1939 and rfc2449
  + IMAP: rfc3501
  + SMTP: rfc2821 (rfc821)
  + Mail file format:  rfc822
  + Multipurpose Internet Mail Extensions (MIME): rfc2045
  + DNS:  rfc819 
  + HTTP: rfc2616 
  + URI:  rfc2396
  + Port usage: /etc/services

These information shall allow manual connection to the daemons:

 $ telnet mail.ispname.net pop3

* archival media
Optimistic (vender provided) storage life numbers on the net:
  2000+ years : Rosseta stone.
   100+ years : acid free paper with ink
   100  years : optical storage  (CD, CD-R)
    30  years : magnetic storage (MO, tape, floppy)
    20  years : phase change optical storage (CD-RW)

(This does not count on the mechanical failures due to handling etc.  
Life is quite dependent on the environment.  Keep them dark, dry, and 
cold.  Also always verify data contents after making back up and always
keep multiple copies in separate safe locations.)

Write cycle
   250,000+ : HDD/Flash
     1,000  : CD-RW
         1  : CD-R, paper

Fire-safe ratings are based on "paper" documents.  Most of the computer
media have less temperature tolerance thus prone to the damage. So make
sure to rely more on multiple secure encrypted copies stored in multiple
locations.  Light, heat and humidity are all bad for computer media.
Keep away from them.

If you need corporate data store, use professional tape.

If you need small personal data back up, use CD-R by the brand name company.
CD-R life is very dependent on the brand.  Also store in dark place.

* iptable tutorials
  check http://www.linuxguruz.org/ especially /iptables/
  Also kernel source Documentation/networking/*

* eql = tun + eth0 related sites review and summary
  http://qos.ittc.ukans.edu/
  http://www.qosforum.com/docs/faq/
  http://www.fibrespeed.net/~mbabcock/linux/qos_tc/
  http://qos.ittc.ukans.edu/howto/
  http://www.ds9a.nl/2.4Routing/

* Wine tutorials
  http://www.samag.com/documents/s=1824/sam0201a/0201a.htm

* upgrade with apt-get
  > Can two Debian 3 systems with the exact same sources.list file have
  > different packages available lists? I have on some packages different
  > version numbers and some packages are missing...
  
  (per Colin Watson <cjwatson@debian.org>)
  Perhaps you're updating with 'apt-get update' rather than 'dselect
  update', and then using some tool (like 'dpkg -p' or dselect) that
  expects dpkg's available database to be up-to-date? 

* fbset for all ttys
  # fbset -t 13334 144 24 29 3 136 6 -a

* two-sided and two-in-one printing of PDF
  gv: 
   print even and odd pages
  mpage
    env variable set to "-bA4 -t -T -2 -Pprn0008" for double-sided A4 with 
    two pages to each sheet
  a2ps is alternative to mpage
  
  CUPS (per Derrick 'dman' Hudson <dman@dman.ddts.net>)
    1) print to file
    2) lp -o number-up=2 -o page-set=even
    3) reinsert pages in printer
    4) lp -o number-up=2 -o page-set=odd
  
* Laptop PC tuning
  anacron

* Hack prebuild deb package

   If a content in a prebuild deb package needs to be removed, move the deb
   package to a temporary directory:

      $ ar x manpages_1.46-1_all.deb
      $ gunzip data.tar.gz
      $ tar -f data.tar --delete ./usr/share/man/man8/ld.so.8.gz
      $ gzip data.tar
      $ ar r manpages_1.46-1_all.deb data.tar.gz
      # dpkg -i manpages_1.46-1_all.deb

* DSL (pppoe) on Debian

   Mailing post indicated that ppoe service of DSL can be made accessible by
   Debian:

      *  compile kernel(mine is 2.4.17) with
         CONFIG_PPP=m
         CONFIG_PPP_SYNC_TTY=m
         CONFIG_SERIAL_NONSTANDARD=y
         CONFIG_N_HDLC=m
      *  module aliases
          alias char-major-108    ppp_generic
          alias /dev/ppp          ppp_generic
          alias tty-ldisc-3       ppp_async
          alias tty-ldisc-14      ppp_synctty
          alias tty-ldisc-13      n_hdlc
      *  bring up eth0 without any IP settings (very important)
      *  /etc/ppp/pppoe.conf: (after adsl-setup)
         CLAMPMSS=no                 ## helps the speed if you hook your
                                     ## machine directly to your modem
         FORCEPING="."               ## the key during the initialization
         USER="user@earthlink.net"   ## one's whole email address
         SYNCHRONOUS=yes             ## works for earthlink
      *  pppoeconf did not work for me.  don't waste your time.
         "pppoe" package is all you need
      *  setup /etc/rc2.d/S14ppp to bring the link up when boot:
          ifconfig eth0 up
          /usr/sbin/adsl-start

    Actually, ppoeconf worked perfectly for Osamu for woody which 
    comes with pppoe support as installed.  Osamu start adsl:
        $ pon dsl-provider

    This needs some clarification before adding to main document.

* Automatic deleting of old msgs in Mutt

   In ~/.muttrc:

      folder-hook mutt.incoming "push 'D~d >14d\n'"

   It deletes messages older than 14 days from the folder mutt.incoming right
   when I open it. Or rather: it marks for deletion.

   Maybe add script for delete all for spam/worm folder.

* More X configuration for my hires 125 DPI screen

*  TrueType font install hints
   Debian specific: http://www.paulandlesley.org/linux/
   Generic: http://www.tldp.org/HOWTO/mini/FDU/index.html
   check defoma package documents (defoma-doc)

* Annoying replacements of apostrophe in Word docs under Mozilla
   You might try installing the msttcorefonts package, which downloads
   Microsoft's free (gratis) TrueType fonts.
   http://fontconfig.org/mozilla/

* Abiword font change (Not elegant)
 1) use dpkg-divert to remove the default Abiword's fonts dir
    (/usr/share/AbiSuite/fonts)
 2) add a symlink to the local TTF dir
   (/usr/share/AbiSuite/fonts -> /usr/local/share/fonts/MS_ttfonts)
   --> defoma should take care of this by now.  So probably not a good tip.

* Japanese UTF-8/X (per Claudio Bley <bley@cs.uni-magdeburg.de>)
 1) add a locale to /etc/locale.gen that supports Japanese characters (e.g.
    ja_JP.UTF-8). (Don't forget to run locale-gen after modifying that file)
    or "dpkg-reconfigure locales"
 2) install the relevant fonts in order to display Japanese characters.
 3) Then, you usually need to set XMODIFIERS to "@im=kinput2" and at least
    LC_CTYPE to a Japanese locale *before* starting the application.
    You may want to do this when starting the X server.
    You may also add "*inputMethod: kinput2" to your X resources file
    - some applications are also using this.
 4) Some applications (such as mlterm) also allow you to change/set up that
    information dynamically at run time (press Ctrl-MBtn-3 in mlterm).
 5) If you started the application, you should press Shift+Space and a
    window should pop up stating that you now may input Japanese characters.
 (Over laps with current contents.) 

* Maybe new chapter/section on Desktop Application
  Openoffice.org Application: very stable
  KDE: mature but funny feel
  GNOME: some stable, others unstable but I like them

* xlibmesa3 and HW accel
  Differ HW compatibility issues to xfree86-common package

* COMPAQ PC BIOS problem
  http://www29.compaq.com/falco/sp_result.asp?Model=2722&Os=0

* Link for Hardware issues RS6000 J30, Ron Johnson <ron.l.johnson@cox.net>
http://www.kernel.org/
http://penguinppc.org/intro.shtml
http://penguinppc.org/projects/hw/
http://oss.software.ibm.com/developer/opensource/linux/projects/ppc/models.php
http://www.debian.org/ports/powerpc/
news:comp.os.linux.powerpc
IBM site: "MCA: POWER- and MCA-based machines do not work at all. 
The only development effort for these machines is located at
http://www.sjdjweis.com/linux/rs6k/"

* Max date on 32 bit Unix/Linux: 2038-01-18 19:14:07

* GIF and UNISYS issue
GIMP issues are already answered but let me draw your attention to the
UNISYS issue.

   http://www.ora.com/infocenters/gff/gff-faq/

I never used it but there are utilities called ungif in Debian.  That
may be what you want :)

   $ apt-cache search ungif

With this, you can use GIF like the Debian website :-)
(We all know the GNU site does not like using these non-LZW GIFs
either.)

* Package split scenario (Check NM/Dev REF)
The groff split example:
  Potato:
    groff
  Woody:
    groff-base Suggests: groff, groff-x11
    groff Depends: groff-base, Suggests: groff-x11
    groff-x11 Depends: groff-base, Suggests: groff

* digital camera = www.gphoto.org 
  Also note that any camera with removable media will work with Linux
  through USB Mass Storage-compatible readers.
  These X-fun apps needs to be summarized in separate documents.

* Encoding Jargons:
  * ASCII      : 7-bit clean                                   (0-0x7f)
  * ISO-8859-1 : 8-bit for western european                    (0-0xff)
  * ISO-8859-15: 8-bit for western european with euro          (0-0xff)
  * ISO-10646-1: Universal Character Set (UCS),        (31 bit, 0-0x7fffffff)
  * UCS-2      : First 16 bit of UCS as straight 2 Octets (unicode: 0-0xffff)
  * UCS-4      : UCS as straight 4 Octets                 (UCS: 0-0x7fffffff)
  * UTF-8      : UCS encoded in 1-6 Octets (most unicode in 3 Octets)

* Byte order:
  * Standard  UCS-2, UCS-4: big endian
  * Microsoft UCS-2, UCS-4: little endian for ix86 (machine-dependent)

* Fonts:
  Non Unicode fonts will help in displaying Unicode documents.  So do 
  not worry too much.  Programs are smarter than us average joe.

  * After installing new fonts in a directory:
   # mkfontdir directory # always
   # xset fp rehash      # if this is on X server's current font path.

  * Display the X server's current font path:
   $ xset -q | sed -e '1,/^Font Path:/d' | sed -e '2,$d' -e 's/^  //'

  * Add a directory to the X server's current font path:
   # xset fp+ directory
   # editor /etc/XF86Config[-4]
     ... add a "FontPath" line to make this permanent

  * Display the installed fonts by menu selecting various font properties:
    $ xfontsel

  * Display the installed fonts by pattern match
    $ xlsfonts -fn fontpattern
    $ xlsfonts -ll -fn font
      ... lists the font properties CHARSET_REGISTRY and 
          CHARSET_ENCODING, which together determine the font's encoding.
  * Display a font page by page:
    $ xfd -fn font


* List of Important fonts:

* UTF-8 xterm
   New xterm in XFree86 4.x.x are UTF-8 ready. Setup xterm for UTF-8,
Add to $HOME/.Xdefaults (Now .Xresource & xrdb):
---------- For typical:
xterm*utf8:   1
xterm*VT100*font:  -misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1
xterm*VT100*wideFont:  -misc-fixed-medium-r-normal-ja-13-125-75-75-c-120-iso10646-1
xterm*VT100*boldFont:  -misc-fixed-bold-r-semicondensed--13-120-75-75-c-60-iso10646-1
---------- For CJK:
xterm*VT100*font:     -Misc-Fixed-Medium-R-Normal--18-120-100-100-C-90-ISO10646-1
xterm*VT100*wideFont: -Misc-Fixed-Medium-R-Normal-ja-18-120-100-100-C-180-ISO10646-1

Debian xterm package also comes with uxterm program:
  uxterm is a wrapper around the xterm(1) program that invokes the latter
  program with the "UXTerm" X  resource  class  set.

UXTerm*VT100*font:     -Misc-Fixed-Medium-R-Normal--18-120-100-100-C-90-ISO10646-1
UXTerm*VT100*wideFont: -Misc-Fixed-Medium-R-Normal-ja-18-120-100-100-C-180-ISO10646-1

Currently no easy way to set up different environment for UXTerm.  See bug #????? 
 (xterm wishlist 14/09/2003)

* Interesting web sites for locale / encoding /post inst related issues
 http://cyberion.net/files/lfs/lfs_frlocale_guide.txt
 http://melkor.dnp.fmph.uniba.sk/~garabik/debian-utf8/howto.html
 http://cerium.raunvis.hi.is/~tpr/linux/debian/   (post inst in general)
 http://www.e-aiyama.com/~toshi/Computer/Linux/Cups.html
 http://www2.ttcn.ne.jp/~yamagen/platform/sarge-s80b/
 http://www.faqs.org/docs/Linux-HOWTO/Font-HOWTO.html
 http://www.ucatv.ne.jp/~taeko/software/gs/Gdevlips.htm
 http://trolls.troll.no/lars/fonts/qt-fonts-HOWTO.html
 http://theregus.com/content/4/26770.html
 
 
* TTF -> BITMAP conversion:
  ttf2bdf utility in freetype1-tools

  For example, to generate a proportional Unicode font for use with
  cooledit:

  # cd /usr/X11R6/lib/X11/fonts/local
  # ttf2bdf ../truetrype/Cyberbit.ttf > cyberbit.bdf
  # bdftopcf -o cyberbit.pcf cyberbit.bdf
  # gzip -9 cyberbit.pcf
  # mkfontdir
  # xset fp rehash

* Get the contents of a src.rpm (Joey Hess <joeyh@debian.org>)
 $ rpm2cpio file.src.rpm | cpio --extract
 $ alien -t file.src.rpm # turn it into a tarball

* What is the URL these days to just get a changelog?
   http://people.debian.org/~noel/changelogs/

* C-lib:
glibc-2.2 supports multi-byte locales, in particular UTF-8 locales.

  Convert old files to UTF-8 for English (ISO-8859-1 encoded texts to UTF-8):
 $ iconv --from-code=ISO-8859-1 --to-code=UTF-8 < old_file > new_file

 record:  GNU powerful
   i2u, u2i : short hand script

 trans
 tcs
 utrans/uhtrans/hutrans
 konwert
 to-utf8: interactive conversion

  Need to test these.
 
