#! /usr/bin/perl

while (<>) { $dict{$1}=$2 if /\s*(.+?)\t+(.+)$/ }
&begin;
@sortedkeys=sort { lc $a cmp lc $b } keys %dict;
my $a;
foreach (@sortedkeys)
{
  if ( $a ne lc(substr($_,0,1)) )
  {
    print "      </taglist>\n      </p>\n    </chapt>\n\n" if (defined $a);
    $a=lc substr($_,0,1);
    print "    <chapt id=\"dgl-dic_$a\">\n\n      <heading>";
    print uc $a, "</heading>\n\n      <p>\n      <taglist>\n";
  }
  print "        <tag>", $_,"\n          <item>", $dict{$_}, "\n";
}
print "      </taglist>\n\n    </chapt>\n\n";

&end;

####################################################################

sub begin
{

print <<End_Of_Text;
<!doctype debiandoc system>

<!--
 Debian GNU/Linux Dctionary 
 Copyright (C) 1997 Ardo van Rangelrooij 
 Released under the terms of the GNU General Public License, 
 version 2 or (at your option) any later. 
 -->

<debiandoc>

  <book>

    <titlepag>

      <title>Словарь Debian GNU/Linux</title>

      <author>
	<name>Ardo van Rangelrooij</name>
	<email>ardo.van.rangelrooij\@tip.nl</email>
      </author>
      <author>
	<name>Oliver Elphick - Maintainer</name>
	<email>olly\@lfix.co.uk</email>
      </author>

      <version>версия 0.1, <date></version>

      <abstract>
	В Словаре Debian GNU/Linux описываются и определяются термины,
	используемые в руководствах Debian GNU/Linux. 
      </abstract>

      <copyright>

	<copyrightsummary>
	  Copyright &copy; 1997 Ardo van Rangelrooij
	</copyrightsummary>

	<p>
	  This manual is free software; you may redistribute it and/or
	  modify it under the terms of the GNU General Public License
	  as published by the Free Software Foundation; either version
	  2, or (at your option) any later version. 
	</p>

	<p>
	  This is distributed in the hope that it will be useful, but
	  <em>without any warranty</em>; without even the implied
	  warranty of merchantability or fitness for a particular
	  purpose.  See the GNU General Public License for more
	  details. 
	</p>

	<p>
	  You should have received a copy of the GNU General Public
	  License with your Debian GNU/Linux system, in
	  <tt>/usr/doc/copyright/GPL</tt>, or with the
	  <prgn>debiandoc-sgml</prgn> source package as the file
	  <tt>COPYING</tt>.  If not, write to the Free Software
	  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
	</p>

      </copyright>

    </titlepag>

    <toc sect>

    <chapt id="dgl-dic_int">

      <heading>Введение</heading>

      <p>
	"об этом руководстве"
      </p>

      <p>
	"где искать более новые версии"
      </p>

      <p>
        "как возникло это руководство"
      </p>

      <p>
        Пожалуйста, все комментарии, критику, предложения, ошибки и т.д. посылайте на 
	<email>olly\@lfix.co.uk</email>.
       Замечания о русском переводе посылайте на <email>paul\@justnews.ru</email>.
      </p>

    </chapt>
End_Of_Text

}

sub end
{
print <<End_Of_Text;
  </book>

</debiandoc>

<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:nil
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:2
sgml-indent-data:t
sgml-parent-document:nil
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
-->

End_Of_Text
}
