#!/usr/bin/env python

import glob
import os.path
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print >>sys.stderr, \
            "call with original language directory and one or more"
        print >>sys.stderr, \
            "translation directories, e.g. %s en ca cs pt_BR" % sys.argv[0]
        sys.exit(-1)
    origlang = sys.argv[1]
    targetlangs = sys.argv[2:]
    filenames = map(os.path.basename, glob.glob("%s/*.dbk" % origlang))
    sizes = {}
    for fn in filenames:
        sizes[fn] = len(open("%s/%s" % (origlang, fn), "r").readlines())
    total = sum(sizes.values())
    for lng in targetlangs:
        stats = 0
        for fn in filenames:
            dbk = open("%s/%s" % (lng, fn), "r").read(2000)
            if dbk.find("\n<!-- English version:") > 0 and \
                    dbk.find("\n<!-- Last translator:"):
                stats += sizes[fn]
        print "%s: ~%d%%." % (lng, int(round(float(stats)/(total/100.))))
